[package]
name = "eco-merge"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
camino.workspace = true
clap.workspace = true
eco-cbz.workspace = true
glob.workspace = true
sanitize-filename.workspace = true
